application: gr-chat
version: 1
runtime: python
api_version: 1

handlers:

- url: /account/[^/]*
  script: account.py
  login: required

- url: /room/[^/]*
  script: room.py
  login: required

- url: /room/[^/]+/msg
  script: message.py
  login: required

- url: /css
  static_dir: css 

- url: .*
  script: main.py
