application: gr-chat
version: 1
runtime: python
api_version: 1

handlers:

- url: /account/[^/]*
  script: account.py
  login: required

- url: /room/[^/]*
  script: room.py
  login: required

- url: /room/[^/]+/leave
  script: room.py
  login: required

- url: /room/[^/]+/msg
  script: message.py
  login: required

- url: /room/[^/]+/topic
  script: message.py
  login: required

- url: /api/room/[^/]+/topic
  script: message.py
  login: required
  
- url: /api/room/[^/]+/msg/[^/]*
  script: message.py

- url: /api/room/[^/]+/msg/
  script: message.py

- url: /css
  static_dir: css 
  expiration: 1d

- url: /js
  static_dir: js
  expiration: 1d

- url: .*
  script: main.py
